### ISSUE TITLE
The sequence in design.fasta is different from the sequence in best.pdb

### ISSUE THREAD

**Issue by Lyang556** [sokrypton/ColabDesign#124]
I am trying to use RFdiffusion in ColabDesign for protein design, and I found that the sequence in design.fasta is different from the sequence in best.pdb, is this normal? Below is one of my results

design.fasta: TYKVVALFTG-----/----
best.pdb: TYKVVALFTGC-----/----
- represents other amino acids
You can see that the sequence of best.pdb has one more C than the sequence of design.fasta

**Comment by Lyang556** [comment]
The --- represents other amino acids and the / represents the chain break

**Comment by sokrypton** [comment]
That shouldn't be the case. Can you share an example input you used?

**Comment by Lyang556** [comment]
@sokrypton Here is an example input

**Comment by Lyang556** [comment]
@sokrypton  Here is an example input.
contigs:10-17/A1008-1031/30-38/0 C22-83
pdb:5zng
copies:1
initial_guess:True

**Comment by Lyang556** [comment]
The other parameters in the Colab RFdiffusion are default.

**Comment by sokrypton** [comment]
Thanks for reporting the bug! I've fixed this in the updated version. Tell me if you still see any issues
