### ISSUE TITLE
Problem in designability_test.py 

### ISSUE THREAD

**Issue by suknamgoong1970** [sokrypton/ColabDesign#126]
I tried to design binder using diffusion.ipynb colab. But I experienced error like this. 

{'pdb':'outputs/Actinbindinger_i5jed_0.pdb','loc':'outputs/Actinbindinger_i5jed','contigs':'A5-39/A51-375:150-150','copies':1,'num_seqs':8,'initial_guess':True,'use_multimer':False,'num_recycles':3,'rm_aa':'C','num_designs':1}
protocol=binder
running proteinMPNN...
running AlphaFold...
Traceback (most recent call last):
  File "/content/colabdesign/rf/designability_test.py", line 198, in <module>
    main(sys.argv[1:])
  File "/content/colabdesign/rf/designability_test.py", line 180, in main
    sub_seq_divided = "".join(np.insert(list(sub_seq),np.cumsum(af_model._lengths[:-1]),"/"))
  File "<__array_function__ internals>", line 180, in insert
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/function_base.py", line 5280, in insert
    raise IndexError(f"index {obj} is out of bounds for axis {axis} "
IndexError: index [360] is out of bounds for axis 0 with size 150
CPU times: user 348 ms, sys: 86.4 ms, total: 434 ms
Wall time: 59.6 s

My parameters are as followed:
Contig : A:100
PDB:1J6Z
HOTSPOTS : A143,A148,A341,A345,A349

num_seqs:8
initial_guess:True
num_recycles:3

Similar error did not occurred a few days ago..

**Comment by sokrypton** [comment]
Thanks for the report. I've pushed a fix! Can you tey again?

**Comment by suknamgoong1970** [comment]
Now it seems to work! Thanks
