### ISSUE TITLE
binder redesign

### ISSUE THREAD

**Issue by avilella** [sokrypton/ColabDesign#13]
Here is a working version of the "binder redesign" idea as posited on Twitter:

http://github.com/avilella/utils/blob/master/af/design.ipynb

I've tried it a few times and the results make me think that there is scope for improvement. What would be the best way to give more chances of this working? Of the three number below, which one should I attempt to increase/decrease first?

```
model.design_3stage(100,50,10)
```

Thx in advance

**Comment by sokrypton** [comment]
I'll close this for now. as we now have options for binder redesign in colabdesign!
Reopen if you see any issues.
