### ISSUE TITLE
mk_af_model: refolding a sequence of a experimental structure using said structure as a template performs miserably

### ISSUE THREAD

**Issue by dandaman** [sokrypton/ColabDesign#167]
Hi,

first of all thank you for providing and maintaining this excellent piece of software :-)

I have encountered a behaviour of mk_af_model.predict() that I found quite puzzling

```python
#aa --> aa seq of 8BO9:A
af_model = mk_af_model(data_dir="data/af",best_metric="dgram_cce")
af_model.prep_inputs(pdb_filename="8BO9_A.pdb")
af_model.predict(seq=aa,
                         num_recycles=1,
                         num_models=1,
                         temp=0.1,
                         verbose=True)
```
Results in:
```
predict models [0] recycles 1 hard 1 soft 0 temp 0.10 seqid 1 loss 2.47 dgram_cce 2.47 plddt 0.34 ptm 0.27 rmsd 20.48
```

I.e. very bad fit to the original structrue. Am I doing something wrong or how can this be explained? 

Any comment is highly appreciated.

All the best,
Daniel

**Comment by sokrypton** [comment]
Hi Daniel,
You need to add:
`mk_af_model(use_templates=True)`

By default the pdb is only used for scoring.

**Comment by dandaman** [comment]
Excellent! That solves it :-)

Thanks for the prompt and helpful response!
