### ISSUE TITLE
af_model.predict failing 

### ISSUE THREAD

**Issue by baptiste-roelens** [sokrypton/ColabDesign#170]
Not sure how recent this is, but the AlphaFold prediction, as implemented for instance in the ProteinMPNN in Jax! notebook does not run on Colab any more.
The following code: 
af_model = mk_af_model(data_dir="/content/params",best_metric="dgram_cce")
af_model.prep_inputs(pdb_filename=pdb_path)
af_model.predict(seq=seq,
                         num_recycles=1,
                         num_models=1,
                         temp=0.1,
                         verbose=True)

results in the following error: 
[/usr/local/lib/python3.10/dist-packages/colabdesign/af/alphafold/model/utils.py](https://localhost:8080/#) in mask_mean(mask, value, axis, drop_mask_channel, eps)
     53   elif axis is None:
     54     axis = list(range(len(mask_shape)))
---> 55   assert isinstance(axis, collections.Iterable), (
     56       'axis needs to be either an iterable, integer or "None"')
     57 

AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by sokrypton** [comment]
Which notebook you are using?

**Comment by baptiste-roelens** [comment]
Looks like I was using an outdated version of the notebook installing ColabDesign v1.1.0, instead of 1.1.1, sorry for the confusion.
