### ISSUE TITLE
I can't see prediction of cyclic peptide example

### ISSUE THREAD

**Issue by kimdn** [sokrypton/ColabDesign#176]
[2023_Cyclic peptide structure prediction and design using AlphaFold](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9980166/ )
mentions 
`"Example scripts for structure prediction, sequence design, and hallucination are available at https://github.com/sokrypton/ColabDesign/blob/main/af/examples/af_cyc_design.ipynb"`

However, I can't see prediction of cyclic peptide example at https://github.com/sokrypton/ColabDesign/blob/main/af/examples/af_cyc_design.ipynb

I see fixbb and hallucination examples only.

**Comment by nachotu** [comment]
Hi! The same happend to me, do you find the code where is the prediction of cyclic peptides?
Thank you

**Comment by sokrypton** [comment]
See this notebook (look at the instructions at the bottom):
https://colab.research.google.com/github/sokrypton/ColabDesign/blob/gamma/af/examples/predict.ipynb

**Comment by kimdn** [comment]
> See this notebook (look at the instructions at the bottom): https://colab.research.google.com/github/sokrypton/ColabDesign/blob/gamma/af/examples/predict.ipynb

@sokrypton 
Thanks. I could run this notebook file with my sequence (APCPPTVLRF) --> (I enclosed my peptide sequence with () since it is thought to be cyclic peptide. 

All predicted pdb files (e.g., best.pdb, model_1_ptm_seed0.pdb etc) are near cyclic but not perfectly closed cyclic as

![image3](https://github.com/user-attachments/assets/0575e787-d171-4513-8944-9a48c7cf18c3)

**Comment by sokrypton** [comment]
@kimdn I think this is just a pymol drawing issue, but they should be close enough to form bond.

**Comment by kimdn** [comment]
> @kimdn I think this is just a pymol drawing issue, but they should be close enough to form bond.

@sokrypton Got it. Above picture was obtained by chimeraX.

With pymol (and showing 'main chain'), indeed I got perfectly closed form of cyclic peptide as 
![image](https://github.com/user-attachments/assets/61009485-9a41-463d-a150-c58e1168c4d0)

as I see AfCycDesign paper
![Screenshot 2024-10-22 at 10 30 40 AM](https://github.com/user-attachments/assets/e4581b4b-6240-4635-b62b-82780e7d380c)


Of course, if I didn't show 'main chain', still I see unclosed form as
![image](https://github.com/user-attachments/assets/938aaa56-1583-43d6-b6d9-27578d68f8d3)

However, I wouldn't worry as you commented.

**Comment by nachotu** [comment]
Thank you very much for the fast response @sokrypton
