### ISSUE TITLE
The Fold Conditioning notebook seems to be broken

### ISSUE THREAD

**Issue by ajasja** [sokrypton/ColabDesign#177]
The [Fold Conditioning notebook ](https://colab.research.google.com/github/sokrypton/ColabDesign/blob/main/rf/examples/diffusion_foldcond.ipynb) seems to be broken, both in main and beta.
I guess the diffusion fails for some reason and then the output can't be displayed. 

Just running everything with the default inputs.
![image](https://github.com/sokrypton/ColabDesign/assets/19926/fb2a947f-cf65-4983-883d-63e6d43c585b)

```
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <timed exec> in <module>
> 
> [<ipython-input-1-4c4e816c817e>](https://localhost:8080/#) in diffuse(self, iterations, mask_loops, mask_contacts, extra_cmd)
>     472       self.cmd_str = " ".join(cmd)
>     473       self._run(self.cmd_str, iterations)
> --> 474     self._plot_pdb(self.buttons["freeze"])
>     475 
>     476   def _run(self, command, steps, num_designs=1):
> 
> [<ipython-input-1-4c4e816c817e>](https://localhost:8080/#) in _plot_pdb(self, change)
>     405       else:
>     406         pdb = f"outputs/{self.path}_0.pdb"
> --> 407         pdb_str = open(pdb,'r').read()
>     408         view.addModel(pdb_str,'pdb')
>     409       if self._plot["color"] == "SSE":
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'outputs/test_0.pdb'
```

**Comment by WhatMadPursuit** [comment]
I am getting the same problem. have you find out a solution? @ajasja @sokrypton

**Comment by WhatMadPursuit** [comment]
it seems that changing the mode from 'manual' to 'automated' solves this problem

**Comment by sokrypton** [comment]
Thanks for report. Will debug.

**Comment by sokrypton** [comment]
Seems to work for me, including manual default settings. What settings that you used that broke it?

**Comment by ajasja** [comment]
Worked for me when I tried it right now. (I guess something updated on the Colab side?).
Anyway closing issue.

**Comment by sokrypton** [comment]
Turns out IPD has issues sometimes, preventing download of database
