### ISSUE TITLE
Does is matter?   ----   RSO notebook ERROR: 'i_pae' not found in ['seq_ent', 'plddt', 'pae', 'exp_res', 'helix']

### ISSUE THREAD

**Issue by Samuel-gwb** [sokrypton/ColabDesign#186]
This error happens during "Binder Sequence Design with AF Multimer filtering" following "Binder Design" on google colab, using 7a5e pdb.

Does this matter ?

**Comment by YangPH0624** [comment]
y
You can try changing binder_model.set_weights(i_pae=1.0) to binder_model.opt["weights"]['i_pae'] = 1.0, which seems to resolve the error. However, I'm not sure if modifying it this way without using the wrapper function will cause any issues. Could someone explain this?
![d52554d657ed25e59c4e7c60295eeb5](https://github.com/user-attachments/assets/563307c5-f89c-4994-a608-fd2aca1fb859)
ou can

**Comment by Samuel-gwb** [comment]
It works ! Thanks !

**Comment by Samuel-gwb** [comment]
It works ! Thanks !
