### ISSUE TITLE
How to input a custom backbone?

### ISSUE THREAD

**Issue by phiweger** [sokrypton/ColabDesign#3]
In the colab notebook we download a PDB example, but how does one input a "custom" backbone? Thanks!

**Comment by RaymondRuff** [comment]
@phiweger This is a fantastic question, I came here to ask it myself. Hopefully if this thread gets enough attention the function will be formally added. For the time being, if I figure out a workaround I will be sure to post it here.

**Comment by sokrypton** [comment]
Just set the pdb id as "", you'll get a prompt to upload your own PDB file :D
