### ISSUE TITLE
File Traceback Error AlphaFold Design

### ISSUE THREAD

**Issue by coopersvajda** [sokrypton/ColabDesign#52]
Hello there,
I have been using the AF Design software for the better part of a week now, and just this evening when trying to run both a partial and full design, I get an error:
---------------------------------------------------------------------------

BadZipFile                                Traceback (most recent call last)

[<ipython-input-4-dd6b5e052673>](https://localhost:8080/#) in <module>()
      1 clear_mem()
----> 2 af_model = mk_afdesign_model(protocol="fixbb")
      3 af_model.prep_inputs(pdb_filename=get_pdb("1TEN"), chain="A")
      4 
      5 print("length",  af_model._len)

6 frames

[/content/colabdesign/af/model.py](https://localhost:8080/#) in __init__(self, protocol, num_seq, num_models, sample_models, recycle_mode, num_recycles, use_templates, best_metric, crop_len, crop_mode, subbatch_size, debug, use_alphafold, use_openfold, loss_callback, data_dir)
     99     self._model_params, self._model_names = [],[]
    100     for model_name in model_names:
--> 101       params = data.get_model_haiku_params(model_name=model_name, data_dir=data_dir)
    102       if params is not None:
    103         if not use_templates:

[/content/colabdesign/af/alphafold/model/data.py](https://localhost:8080/#) in get_model_haiku_params(model_name, data_dir)
     38   if os.path.isfile(path):
     39     with open(path, 'rb') as f:
---> 40       params = np.load(io.BytesIO(f.read()), allow_pickle=False)
     41     return utils.flat_params_to_haiku(params)
     42   else:

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    431             stack.pop_all()
    432             ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
--> 433                           pickle_kwargs=pickle_kwargs)
    434             return ret
    435         elif magic == format.MAGIC_PREFIX:

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in __init__(self, fid, own_fid, allow_pickle, pickle_kwargs)
    187         # Import is postponed to here since zipfile depends on gzip, an
    188         # optional component of the so-called standard library.
--> 189         _zip = zipfile_factory(fid)
    190         self._files = _zip.namelist()
    191         self.files = []

[/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py](https://localhost:8080/#) in zipfile_factory(file, *args, **kwargs)
    110     import zipfile
    111     kwargs['allowZip64'] = True
--> 112     return zipfile.ZipFile(file, *args, **kwargs)
    113 
    114 

[/usr/lib/python3.7/zipfile.py](https://localhost:8080/#) in __init__(self, file, mode, compression, allowZip64, compresslevel)
   1256         try:
   1257             if mode == 'r':
-> 1258                 self._RealGetContents()
   1259             elif mode in ('w', 'x'):
   1260                 # set the modified flag so central directory gets written

[/usr/lib/python3.7/zipfile.py](https://localhost:8080/#) in _RealGetContents(self)
   1323             raise BadZipFile("File is not a zip file")
   1324         if not endrec:
-> 1325             raise BadZipFile("File is not a zip file")
   1326         if self.debug > 1:
   1327             print(endrec)

BadZipFile: File is not a zip file

Did something on the backend recently change such as a file rearrangement?

**Comment by sokrypton** [comment]
Hmmmm... the only reason this would happen is if there was an error during the download of the weights. 
Can you try again?

**Comment by coopersvajda** [comment]
I have been running into GPU usage issues with Colab, so I will spend the morning getting everything moved over into our cluster and I'll let you know if I get any further errors when I have it properly re-downloaded there.

**Comment by sokrypton** [comment]
I'll close the issue for now, but feel free to reopen if the issue continues!

Thanks,
