### ISSUE TITLE
Binder Hallucination Memory Leak

### ISSUE THREAD

**Issue by RaymondRuff** [sokrypton/ColabDesign#73]
I have written a little loop to generate as many binders as I want for further refinement/testing but am running into what seems to be a memory leak that causes the program to crash. Consistently, following ~332 loops the software exhausts all VRAM resources and exits. This happens on machines with anywhere from 16 to 48GB VRAM. I have used `clear_mem()` and `model.restart()` in the loop to try and free the resources but to no avail. Further, I have tried using `%reset -f` to ablate namespace. Has anyone experienced anything similar? Any advice on how to avoid this buildup?
Thanks!

**Comment by sokrypton** [comment]
Thanks for the report @RaymondRuff 
clear_mem() is suppose to clear any GPU VRAM used, it doesn't clear the RAM...

I'll investigate where there might be a RAM leak.

**Comment by sokrypton** [comment]
There is still some leak... but it is much better now with the latest commit:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/4187522/189474901-51d2b345-e02d-4a95-b771-9d0a147717ca.png">

The critical change is here:
https://github.com/sokrypton/ColabDesign/blob/main/colabdesign/shared/utils.py#L15


Tell me if you still see memory issues.

**Comment by RaymondRuff** [comment]
That appears to have doe the trick! I will keep an eye as I push out further but so far it appears to be working. Thank you very much for your prompt response and solution, I definitely expected a bit more head-scratching! 

As a side note, would you be able to help me understand what exactly seqsep does? Many thanks

**Comment by sokrypton** [comment]
for binder hallucination there are two "con" options.
"con" and "i_con". 
the first is tries to maximize [num]ber of [con]tacts with cb-cb distance < [cutoff] per position with sequence seperation > [seqsep]. 
the latter tries to maximize [num]ber of contacts at interface between binder and target, per binder position (number of positions controled with [num_pos]) with cb-cb distance < [cutoff].
