### ISSUE TITLE
Sidechain rmsd loss throws out error

### ISSUE THREAD

**Issue by ardagoreci** [sokrypton/ColabDesign#87]
Firstly, thank you for this codebase; it is greatly accelerating our research. 

I am trying to add a sidechain loss to certain residues in partial hallucination, but I am getting an error deep within the code. 

When I prep_inputs with use_sidechains = True, I get the following error:
TypeError: take requires ndarray or scalar arguments, got <class 'colabdesign.af.alphafold.model.r3.Rigids'> at position 0.

I do not have the technical expertise to dive into the code and fix this issue, please help!

<img width="1012" alt="Screen Shot 2022-10-13 at 16 04 38" src="https://user-images.githubusercontent.com/98056717/195634384-211b267f-e326-47c0-bbab-72428c912fa3.png">

**Comment by sokrypton** [comment]
Thanks!
This bug should be fixed now in v1.0.8 and v1.10

**Comment by ardagoreci** [comment]
Thank you!!
