### ISSUE TITLE
Homooligomer design in ProteinMPNN

### ISSUE THREAD

**Issue by alessandronascimento** [sokrypton/ColabDesign#96]
Hi developers,

First, thanks for this awesome tool! I'm just starting to use it!

In first tests, I tried to design a sequence from a structure using a GTPase (PDB ID 6N12, chains A and B). However, I'm getting this error message below in cell "Run ProteinMPNN to design new sequences for given backbone". I tried different PDB files with same issue. 

Any ideas about what could be going on and hot to get around it?

Thanks in advance,

Alessandro

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<timed exec> in <module>

[/content/colabdesign/mpnn/model.py](https://localhost:8080/#) in prep_inputs(self, pdb_filename, chain, homooligomer, ignore_missing, fix_pos, inverse, rm_aa, verbose, **kwargs)
     80 
     81     if homooligomer:
---> 82       assert min(self._lengths) == max(self._lengths)
     83       self._tied_lengths = True
     84       self._len = self._lengths[0]

AssertionError:

**Comment by sokrypton** [comment]
This means the two chains are of different length. You'll first need to modify the pdb so they are the same.

**Comment by alessandronascimento** [comment]
Thanks a lot @sokrypton ! Makes a lot of sense!!!

I'm closing the issue!

All the best!
